os: linux
sudo: required
language:
  - cpp
services:
  - docker

compiler:
  - gcc

env:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug

jobs:
  include:
    - name: "build"
      script:
        - cmake CMakeLists.txt

        - cmake --build .
    - name: "tests"
      script:
        - docker run -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/tests.sh

notifications:
  email: false
