os: linux
dist: xenial
sudo: required
language:
  - cpp
services:
  - docker

addons:
  apt:
    sources:
      - deadsnakes
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
      - llvm-toolchain-trusty-4.0
    packages:
      - build-essential
      - cmake
      - cmake-data
      - clang-4.0
      - g++-6
      - gcc-6
      - libc6-dev
      - xorg-dev
      - libx11-dev
      - libxmu-dev
      - libxi-dev
      - libgl1-mesa-dev
      - libosmesa-dev
      - x11proto-core-dev
      - lcov
      - ggcov

jobs:
  include:

    - name: "tests"
      script:
        - docker run -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/tests.sh
    - name: "quality"
      script:
        - ./scripts/genenv.sh
        - docker run --env-file .env -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/duplication.sh

notifications:
  email: false
