os: linux
dist: xenial
sudo: required
language:
  - cpp
services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libfreetype6-dev libxrandr-dev libudev-dev libsfml-dev libogg-dev libflac-dev libvorbis-dev libopenal-dev

jobs:
  include:

    - name: "tests"
      script:
        - docker run -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/tests.sh
    - name: "quality"
      script:
        - ./scripts/genenv.sh
        - docker run --env-file .env -v `pwd`:`pwd` -w `pwd` -t rusdevops/bootstrap-cpp scripts/duplication.sh

notifications:
  email: false
